- Analytics/Client.cs
- Analytics/Model/Alias.cs
- Analytics/Model/BaseAction.cs
- Analytics/Model/Group.cs
- Analytics/Model/Identify.cs
- Analytics/Model/Page.cs
- Analytics/Model/Screen.cs
- Analytics/Model/Track.cs
This also moves userId and anonymousId to baseAction, since it's common to all
> Respect anonymous ID

- Analytics/Client.cs
- Analytics/Request/BlockingRequestHandler.cs
- Analytics/Stats/Statistics.cs
This resolves https://github.com/segmentio/Analytics.NET/issues/41
> Make counters unsigned and ensure they overflow

- Analytics/Client.cs
This resolves https://github.com/segmentio/Analytics.NET/issues/39 and https://github.com/segmentio/Analytics.NET/issues/40
> Unify phrasing and capitalization

- Analytics/Client.cs
- Analytics/Logger.cs
- Analytics/Model/Group.cs
- Analytics/Model/Identify.cs
- Analytics/Model/Page.cs
- Analytics/Model/Screen.cs
- Analytics/Model/Track.cs
- Test/ActionTests.cs
- Test/FlushTests.cs
> Take IDictionary<string, object> instead of requiring Dict

- Analytics/Client.cs
- Analytics/Request/BlockingRequestHandler.cs
- Analytics/Stats/Statistics.cs
This resolves https://github.com/segmentio/Analytics.NET/issues/46
> Make signed int counters overflow to zero

- Analytics/Config.cs
User can call SetHost() function to change REST API server.
The parameter is a domain name or IP address of server.
> Add SetHost() function into Config class.

- Analytics/Request/BlockingRequestHandler.cs
- Test.E2E/Test.E2E.csproj
- Add retries with exponential backoff
- Handle HTTP Response codes are appropriately.
> Handling network errors

- Analytics/Config.cs
- Analytics/Request/BlockingRequestHandler.cs
- Test.Net35/ConnectionTests.cs
- Test.Net45/ConnectionTests.cs
- Test.NetStandard20/ConnectionTests.cs
- Test.UniversalApp/ConnectionTests.cs
- Test/ConnectionTests.cs
Compress request content with GZip algorithm
> Gzip header

- Analytics/Analytics.csproj
This will enable us to build the library on any operating system supported by the .NET Core SDK.
> LAPP-62 Adding nuget package ReferenceAssemblies

- Analytics/Client.cs
- Analytics/Config.cs
- Analytics/Request/FakeRequestHandler.cs
- Test.Net35/ClientTests.cs
- Test.Net35/Program.cs
- Test.Net45/ClientTests.cs
- Test.NetStandard20/ClientTests.cs
If this configuration is true the data is not sent to the segment servers. the default value is false.
> LAPP-39 Adding Send configuration

- Analytics/Analytics.cs
- Analytics/Analytics.csproj
- CHANGELOG.md
> Releasing 3.4.1-alpha

- Analytics/Client.cs
- Analytics/Config.cs
- Test.Net35/ClientTests.cs
- Test.Net45/ClientTests.cs
- Test.NetStandard20/ClientTests.cs
> Issue#140 change confusing config variable name

- Analytics/Analytics.csproj
To resolve suggestions in issue: https://github.com/segmentio/Analytics.NET/issues/153
> 153 updating metadata

- Analytics/Request/BlockingRequestHandler.cs
- Test.Net35/ConnectionTests.cs
- Test.Net35/Test.Net35.csproj
- Test.Net35/WebServer.cs
- Test.Net45/ConnectionTests.cs
- Test.NetStandard20/ConnectionTests.cs
- Test.NetStandard20/Test.NetStandard20.csproj
- Test.UniversalApp/ConnectionTests.cs
- Test/ConnectionTests.cs
> Issue#154 catch post async network exceptions and retry

- Analytics/Client.cs
- Analytics/Config.cs
- Analytics/Request/BlockingRequestHandler.cs
- Test.Net35/ConnectionTests.cs
- Test.Net45/ConnectionTests.cs
- Test.NetStandard20/ConnectionTests.cs
- Test.UniversalApp/ConnectionTests.cs
- Test/ConnectionTests.cs
Issue #163 Added logs in exception so as to clarify which exception is thrown when HTTP request fails. Also added property to config so as to configure Max Retry Time in Backo so as to configure Time span to retry HTTP request in case of request Failure when flush
> Issue#163 events not sent to segment servers unexpected status code

- Analytics/Model/Alias.cs
- Analytics/Model/Group.cs
- Analytics/Model/Page.cs
- Analytics/Model/Screen.cs
- Analytics/Model/Track.cs
Changed private fields of concrete BaseAction implementations to Properties so as to be accessible for public use
> Issue#174 changing fields of concrete implementations of base action to properties

- .circleci/config.yml
- Analytics.NET.sln
- Analytics/Analytics.csproj
- Analytics/Extensions/ServiceCollectionExtension.cs
- Test.Net50/ActionTests.cs
- Test.Net50/Actions.cs
- Test.Net50/ClientTests.cs
- Test.Net50/ConfigTests.cs
- Test.Net50/ConnectionTests.cs
- Test.Net50/Constants.cs
- Test.Net50/Extensions/ServiceCollectionExtensionTests.cs
- Test.Net50/Flush/AsyncIntervalFlushHandlerTests.cs
- Test.Net50/FlushTests.cs
- Test.Net50/Request/BackoTests.cs
- Test.Net50/Request/BlockingRequestHandlerTest.cs
- Test.Net50/Stats/StatisticsTests.cs
- Test.Net50/Test.Net50.csproj
Added support and test for .NET 5.0 framework allowing compatibility with more .net applications and platforms with more recent sdk's
> Issue#177 net 50 support

- Analytics/Config.cs
- Test.Net35/ConfigTests.cs
- Test.Net45/ConfigTests.cs
- Test.Net50/ConfigTests.cs
- Test.NetStandard20/ConfigTests.cs
Added Get functionality to properties of Config object and added unit tests for it
> issue#170 Added Get functionality to properties of Config object and added unit tests for it

- Analytics/Analytics.csproj
- CHANGELOG.md
> Update changelog 14/07/2021

- Analytics/Request/BlockingRequestHandler.cs
Added exception handling in case an OperationCancelledException raises and also if an unknown exception is risen, it is handled.
> Issue#179 Adding exception handle regarding operation canceled exception

- CHANGELOG.md
> Update CHANGELOG.md with last changes

- Analytics/Analytics.cs
Fix issue #196 
- Allow a mocked Client
> Change private method to public on Analytics
